# Generated by Django 5.2.4 on 2025-08-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(blank=True)),
                ('mass', models.FloatField(blank=True)),
                ('gravity', models.FloatField(blank=True)),
                ('comp', models.JSONField(blank=True)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exo.profiles')),
            ],
        ),
    ]
