# Generated by Django 5.2.4 on 2025-08-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0002_planet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='username',
            new_name='display_name',
        ),
    ]
