# Generated by Django 5.2.4 on 2025-08-05 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exo", "0003_rename_username_profiles_display_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="planet",
            name="prof",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planets",
                to="exo.profiles",
            ),
        ),
        migrations.AlterField(
            model_name="profiles",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
