# Generated by Django 5.2.4 on 2025-08-05 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exo", "0004_alter_planet_prof_alter_profiles_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planet",
            old_name="prof",
            new_name="profile",
        ),
    ]
