# Generated by Django 5.2.4 on 2025-08-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0005_rename_prof_planet_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='p_type',
            field=models.TextField(blank=True),
        ),
    ]
