# Generated by Django 5.2.4 on 2025-08-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0006_planet_p_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='pfp',
            field=models.TextField(default='Red Planet'),
        ),
    ]
