# Generated by Django 5.2.4 on 2025-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0007_profiles_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='pfp',
            field=models.TextField(choices=[('Red Planet', 'Red Planet'), ('Purple Planet', 'Purple Planet'), ('Green Planet', 'Green Planet')], default='Red Planet'),
        ),
    ]
