# Generated by Django 5.2.4 on 2025-08-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0008_alter_profiles_pfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='exo.planet')),
                ('p10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p10', to='exo.planet')),
                ('p11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p11', to='exo.planet')),
                ('p12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p12', to='exo.planet')),
                ('p13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p13', to='exo.planet')),
                ('p14', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p14', to='exo.planet')),
                ('p15', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p15', to='exo.planet')),
                ('p16', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p16', to='exo.planet')),
                ('p17', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p17', to='exo.planet')),
                ('p18', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p18', to='exo.planet')),
                ('p19', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p19', to='exo.planet')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='exo.planet')),
                ('p20', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p20', to='exo.planet')),
                ('p3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p3', to='exo.planet')),
                ('p4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p4', to='exo.planet')),
                ('p5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p5', to='exo.planet')),
                ('p6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p6', to='exo.planet')),
                ('p7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p7', to='exo.planet')),
                ('p8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p8', to='exo.planet')),
                ('p9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p9', to='exo.planet')),
            ],
        ),
    ]
