# Generated by Django 5.2.4 on 2025-08-17 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0009_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck_prof', to='exo.profiles'),
        ),
    ]
